# Generated by Django 4.1.7 on 2023-03-01 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.AutoField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=255)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="EmployeeManagerApp.employee",
                    ),
                ),
            ],
        ),
    ]
